name: Issue comment
on:
  issues:
    types: [opened]
    
jobs:
  comment_with_action:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Context Step
        run: echo "${{ toJSON(github.event) }}"
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ toJSON(github.event.issue.number) }}
          body: |
            This is a multi-line comment
            - With GitHub **Markdown** :sparkles:
            - Something here :eyes:
            
