name: Debug Context Workflow
on: workflow_dispatch
jobs:
  debug_context:
    runs-on: ubuntu-latest
    env:
      HEH: foobar
      SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
    steps:
      - name: Debug Context Step
        run: echo "${{ toJSON(github.event) }}"
      - name: Check environmental variable
        run: echo "HEH is $HEH (${{ env.HEH }}) $SUPER_SECRET"


